spring:
  application:
    name: aerotool-application
  datasource:
    url: jdbc:postgresql://localhost:5432/aerotool
    username: aerotool-app
    password: aerotool-app
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialetc: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

queries:
  sql:
    user-dao:
      insert:
        user: >
            INSERT INTO aerotool_platform.user(id, name, role, promptuary_login) VALUES (?, ?, ?::aerotool_platform.user_role, ?)
      select:
        user-and-login-and-password-from-promptuary-by-promptuary-login: >
          SELECT u.id, u.name, u.role, p.login, p.password FROM aerotool_platform.user u INNER JOIN aerotool_platform.promptuary p ON u.promptuary_login = p.login WHERE u.promptuary_login= ?
        user-all: >
          SELECT * FROM aerotool_platform.user
      delete:
        user-by-promptuary:
          DELETE FROM aerotool_platform.user WHERE promptuary_login=?
    tool-dao:
      insert:
        tool: >
            INSERT INTO aerotool_platform.tool(id, name, description, type) VALUES (?, ?, ?, ?::aerotool_platform.tool_type)
      update:
        tool: >
            UPDATE aerotool_platform.tool SET name=?, description=?, type=?::aerotool_platform.tool_type WHERE id=?
      select:
        tool-by-id: >
          SELECT * FROM aerotool_platform.tool WHERE id=?
        tool-all: >
          SELECT * FROM aerotool_platform.tool
      delete:
        tool-by-id: >
          DELETE FROM aerotool_platform.tool WHERE id=?
    tool-item-dao:
        insert:
            tool-item: >
                INSERT INTO aerotool_platform.tool_item(id, patrimony, situation, locate_id, tool_id) VALUES (?, ?, ?::aerotool_platform.tool_situation, ?, ?)
        update:
            tool-item: >
                UPDATE aerotool_platform.tool_item SET patrimony=?, situation=?::aerotool_platform.tool_situation, locate_id=?, tool_id=? WHERE id=?
        select:
            tool-item-by-id: >
                SELECT * FROM aerotool_platform.tool_item WHERE id=?
            tool-item-all: >
                SELECT * FROM aerotool_platform.tool_item
        delete:
            tool-item-by-id: >
                DELETE FROM aerotool_platform.tool_item WHERE id=?
    locate-dao:
      insert:
        locate: >
            INSERT INTO aerotool_platform.locate(id, name, description) VALUES (?, ?, ?)
      select:
        find-all: >
            SELECT * FROM aerotool_platform.locate
        find-by-id: >
            SELECT * FROM aerotool_platform.locate WHERE id=?