spring:
  application:
    name: aerotool-application
  datasource:
    url: jdbc:postgresql://localhost:5432/aerotool
    username: aerotool-app
    password: aerotool-app
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialetc: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

queries:
  sql:
    tool-dao:
      insert:
        tool: >
            INSERT INTO aerotool_platform.tool(id, name, description, type) VALUES (?, ?, ?, ?::aerotool_platform.tool_type)
      update:
        tool: >
            UPDATE aerotool_platform.tool SET name=?, description=?, type=?::aerotool_platform.tool_type WHERE id=?
      select:
        tool-by-id: >
          SELECT * FROM aerotool_platform.tool WHERE id=?
        tool-all: >
          SELECT * FROM aerotool_platform.tool
      delete:
        tool-by-id: >
          DELETE FROM aerotool_platform.tool WHERE id=?